# Generated by Django 3.0.8 on 2020-09-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('d_type', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[('H', 'Wyrmling'), ('v', 'Very Young'), ('y', 'Young'), ('J', 'Juvenile'), ('Y', 'Young Adult'), ('A', 'Adult'), ('O', 'Old'), ('V', 'Very Old'), ('A', 'Ancient'), ('W', 'Wyrm'), ('G', 'Great Wyrm')], default=0, max_length=1)),
                ('lore', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adventurer_type', models.CharField(choices=[('F', 'Fighter'), ('W', 'Wizard'), ('M', 'Monk'), ('R', 'Ranger'), ('B', 'Barbarian'), ('T', 'Thief'), ('C', 'Cleric')], default='F', max_length=1)),
                ('dragon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Dragon')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
