# Generated by Django 3.0.8 on 2020-09-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_loot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('magic', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='date',
            field=models.DateField(verbose_name='Date of incursion'),
        ),
        migrations.AddField(
            model_name='dragon',
            name='loot',
            field=models.ManyToManyField(to='main_app.Loot'),
        ),
    ]
