# Generated by Django 3.0.8 on 2020-09-24 06:11

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_adventurers_loot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurers',
            old_name='cat',
            new_name='dragon',
        ),
        migrations.AddField(
            model_name='adventurers',
            name='lootnumber',
            field=models.PositiveSmallIntegerField(default=main_app.models.lootRand),
        ),
    ]
