# Generated by Django 3.0.8 on 2020-09-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200924_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loot',
            name='magic',
        ),
    ]
